apiVersion: v1
kind: Secret
metadata:
  name: drone-secret
  namespace: drone
type: Opaque
stringData:
  # ⚠️ 重要：部署前必须修改这些值！
  
  # 1. RPC Secret - 用于 Server 和 Runner 之间的通信
  # 生成方法: openssl rand -hex 16
  DRONE_RPC_SECRET: "571e1ae181421bd9d87936338c662092"
  
  # 2. Admin 用户配置
  # 格式: username:<用户名>,admin:true
  DRONE_USER_CREATE: "username:admin,admin:true"
  
  # 3. 如果使用 GitHub，需要配置 OAuth（可选）
  # DRONE_GITHUB_CLIENT_ID: "your-github-client-id"
  # DRONE_GITHUB_CLIENT_SECRET: "your-github-client-secret"
  
  # 4. 如果使用 GitLab，需要配置 OAuth（可选）
  # DRONE_GITLAB_CLIENT_ID: "your-gitlab-client-id"
  # DRONE_GITLAB_CLIENT_SECRET: "your-gitlab-client-secret"
  
  # 5. 如果使用 Gitea，需要配置 OAuth（可选）
  # DRONE_GITEA_CLIENT_ID: "your-gitea-client-id"
  # DRONE_GITEA_CLIENT_SECRET: "your-gitea-client-secret"
