apiVersion: v1
kind: Service
metadata:
  name: drone-server
  namespace: drone
  labels:
    app: drone-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: drone-server
